name: Build

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    name: Containers
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        network-version:
          - name: v28
            lotus-commit: ad39d8707d9c8efa567cd4306140988930f1ef57
            lotus-versions:
              - v1.23.1
              - v1.23.2
              - v1.23.3
              - v1.23.4-rc1
        sector-size:
          - '8388608'
        platform:
          - linux/amd64,linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ matrix.platform }}
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for Lotus ${{ matrix.lotus-version }} Sector Size ${{ matrix.sector-size }}
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=fil-proof-params-${{ matrix.lotus-version }}-${{ matrix.sector-size }}
      - uses: actions/github-script@v6
        with:
          script: |
            for (lotus-version in matrix.network-version.lotus-versions) {
              console.log(`fil-proof-params-${lotus-version }-${matrix.sector-size }`)
            }
      - name: Build image for Lotus ${{ matrix.lotus-version }} Sector Size ${{ matrix.sector-size }}
        uses: docker/build-push-action@v4
        with:
          context: proof-params-cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.platform }}
          build-args: |
            LOTUS_VERSION=${{ matrix.lotus-version }}
            SECTOR_SIZE=${{ matrix.sector-size }}
